// Machine generated by antispice.
const FUNCTION_NAME = __FUNCTION_NAME__;
const STATE_SIZE = __STATE_SIZE__;
const POTENTIAL_INDICES = Object.freeze(__POTENTIALS__);
const CURRENT_INDICES = Object.freeze(__CURRENTS__);
const AUXILIARY_INDICES = Object.freeze(__AUXILIARIES__);
const AUXILIARY_COUNT = __AUXILIARY_COUNT__;
const POTENTIAL_COUNT = Object.keys(POTENTIAL_INDICES).length;
const OFFSETS = Object.freeze({
  stageDerivatives: __STAGE_DERIVATIVES__,
  state: __PREVIOUS_STATE__,
  updatedStageDerivatives: __UPDATED_STAGE_DERIVATIVES__,
  nextState: __NEXT_STATE__,
  residual: __RESIDUAL__,
  jacobian: __JACOBIAN__,
  auxiliaryValues: __AUXILIARY_VALUES__,
});

const DEFAULT_MATH_IMPORTS = Object.freeze({
  abs: Math.abs,
  acos: Math.acos,
  acosh: Math.acosh,
  asin: Math.asin,
  asinh: Math.asinh,
  atan: Math.atan,
  atan2: Math.atan2,
  atanh: Math.atanh,
  cos: Math.cos,
  cosh: Math.cosh,
  exp: Math.exp,
  log: Math.log,
  powf: Math.pow,
  powi: (base, exponent) => Math.pow(base, Number(exponent)),
  sin: Math.sin,
  sinh: Math.sinh,
  tan: Math.tan,
  tanh: Math.tanh,
});

class CircuitStateView {
  constructor(owner) {
    this._owner = owner;
  }

  get vector() {
    this._owner._refreshViews();
    return this._owner.vectors.state;
  }

  potential(net) {
    if (net === "0") return 0;
    const index = POTENTIAL_INDICES[net];
    if (index === undefined) throw new RangeError(`Unknown net: ${net}`);
    return this.vector[index];
  }

  setPotential(net, value) {
    if (net === "0") throw new RangeError("The reference potential is fixed at zero");
    const index = POTENTIAL_INDICES[net];
    if (index === undefined) throw new RangeError(`Unknown net: ${net}`);
    this.vector[index] = value;
  }

  current(reference, port) {
    const ports = CURRENT_INDICES[reference];
    if (ports === undefined || ports[port] === undefined) {
      throw new RangeError(`Unknown element port: ${reference}.${port}`);
    }
    return this.vector[ports[port]];
  }

  setCurrent(reference, port, value) {
    const ports = CURRENT_INDICES[reference];
    if (ports === undefined || ports[port] === undefined) {
      throw new RangeError(`Unknown element port: ${reference}.${port}`);
    }
    this.vector[ports[port]] = value;
  }

  snapshot() {
    const vector = Array.from(this.vector);
    const potentials = {"0": 0};
    for (const [net, index] of Object.entries(POTENTIAL_INDICES)) {
      potentials[net] = vector[index];
    }
    const currents = {};
    for (const [reference, ports] of Object.entries(CURRENT_INDICES)) {
      currents[reference] = {};
      for (const [port, index] of Object.entries(ports)) {
        currents[reference][port] = vector[index];
      }
    }
    return {vector, potentials, currents};
  }
}

export class __CLASS_NAME__ {
  static async instantiate(source, imports = {}) {
    const mergedImports = {
      ...imports,
      math: {...DEFAULT_MATH_IMPORTS, ...(imports.math || {})},
    };
    let instance;
    if (source instanceof WebAssembly.Instance) {
      instance = source;
    } else if (source instanceof WebAssembly.Module) {
      instance = await WebAssembly.instantiate(source, mergedImports);
    } else {
      let bytes = source;
      if (typeof Response !== "undefined" && source instanceof Response) {
        bytes = await source.arrayBuffer();
      }
      const result = await WebAssembly.instantiate(bytes, mergedImports);
      instance = result.instance;
    }
    return new __CLASS_NAME__(instance);
  }

  constructor(instance) {
    this.instance = instance;
    this.memory = instance.exports.memory;
    this._stepFunction = instance.exports[FUNCTION_NAME];
    this._stationaryFunction = instance.exports.stationary_evaluate;
    this._auxiliaryFunction = instance.exports.evaluate_auxiliaries;
    this._linearSolve = instance.exports.dense_lu_solve;
    if (!(this.memory instanceof WebAssembly.Memory)) {
      throw new TypeError("The WebAssembly module does not export memory");
    }
    if (typeof this._stepFunction !== "function") {
      throw new TypeError(`The WebAssembly module does not export ${FUNCTION_NAME}`);
    }
    if (typeof this._linearSolve !== "function") {
      throw new TypeError("The WebAssembly module does not export dense_lu_solve");
    }
    if (typeof this._stationaryFunction !== "function") {
      throw new TypeError("The WebAssembly module does not export stationary_evaluate");
    }
    if (AUXILIARY_COUNT && typeof this._auxiliaryFunction !== "function") {
      throw new TypeError("The WebAssembly module does not export evaluate_auxiliaries");
    }
    this._buffer = null;
    this.vectors = null;
    this._operatingPreviousState = new Float64Array(STATE_SIZE);
    this._operatingCorrection = new Float64Array(STATE_SIZE);
    this._transientPreviousStage = new Float64Array(2 * STATE_SIZE);
    this._transientCorrection = new Float64Array(2 * STATE_SIZE);
    this._adaptiveInitialState = new Float64Array(STATE_SIZE);
    this._adaptiveInitialStage = new Float64Array(2 * STATE_SIZE);
    this._adaptiveFullState = new Float64Array(STATE_SIZE);
    this._newtonResult = {error: 0, scale: 0, residualNorm: 0};
    this._refreshViews();
    this.state = new CircuitStateView(this);
  }

  _refreshViews() {
    if (this._buffer === this.memory.buffer) return;
    this._buffer = this.memory.buffer;
    this.vectors = Object.freeze({
      stageDerivatives: new Float64Array(this._buffer, OFFSETS.stageDerivatives, 2 * STATE_SIZE),
      state: new Float64Array(this._buffer, OFFSETS.state, STATE_SIZE),
      updatedStageDerivatives: new Float64Array(this._buffer, OFFSETS.updatedStageDerivatives, 2 * STATE_SIZE),
      nextState: new Float64Array(this._buffer, OFFSETS.nextState, STATE_SIZE),
      residual: new Float64Array(this._buffer, OFFSETS.residual, 2 * STATE_SIZE),
      jacobian: new Float64Array(this._buffer, OFFSETS.jacobian, 4 * STATE_SIZE * STATE_SIZE),
      auxiliaryValues: new Float64Array(this._buffer, OFFSETS.auxiliaryValues, AUXILIARY_COUNT),
    });
  }

  reset(value = 0) {
    this._refreshViews();
    for (const vector of Object.values(this.vectors)) vector.fill(value);
  }

  _evaluateAuxiliaries(time) {
    if (!AUXILIARY_COUNT) return this.vectors.auxiliaryValues;
    this._auxiliaryFunction(
      OFFSETS.state,
      OFFSETS.stageDerivatives + STATE_SIZE * Float64Array.BYTES_PER_ELEMENT,
      time,
      OFFSETS.auxiliaryValues,
    );
    return this.vectors.auxiliaryValues;
  }

  initializeOperatingPoint(time, options = {}) {
    const {
      maxIterations = 20,
      residualTolerance = 1e-10,
      pivotTolerance = 1e-14,
      minimumStepMultiplier = 2 ** -20,
    } = options;
    if (!Number.isFinite(time)) throw new RangeError("Operating-point time must be finite");
    if (!Number.isFinite(residualTolerance) || !(residualTolerance > 0)) throw new RangeError("residualTolerance must be positive and finite");
    this._refreshViews();
    const residualNorm = () => {
      let norm = 0;
      for (let index = 0; index < STATE_SIZE; ++index) {
        norm = Math.max(norm, Math.abs(this.vectors.residual[index]));
      }
      return norm;
    };
    const finish = (iterations, norm) => {
      this.vectors.stageDerivatives.fill(0);
      this.vectors.updatedStageDerivatives.fill(0);
      this.vectors.nextState.set(this.vectors.state);
      return {iterations, converged: true, residualNorm: norm};
    };
    let norm = Infinity;
    let iterations = 0;
    for (; iterations < maxIterations; ++iterations) {
      this._stationaryFunction(
        OFFSETS.state,
        time,
        OFFSETS.residual,
        OFFSETS.jacobian,
      );
      norm = residualNorm();
      if (!Number.isFinite(norm)) throw new Error(`Operating-point residual is non-finite at t=${time}`);
      if (norm <= residualTolerance) return finish(iterations, norm);
      const status = this._linearSolve(
        OFFSETS.jacobian,
        OFFSETS.residual,
        STATE_SIZE,
        pivotTolerance,
      );
      if (status === 1) throw new Error(`Operating-point Jacobian is singular or ill-conditioned at t=${time}`);
      if (status !== 0) throw new Error(`Operating-point Jacobian contains a non-finite pivot at t=${time}`);

      const previousState = this._operatingPreviousState;
      const correction = this._operatingCorrection;
      previousState.set(this.vectors.state);
      correction.set(this.vectors.residual.subarray(0, STATE_SIZE));
      let multiplier = 1;
      let improved = false;
      while (multiplier >= minimumStepMultiplier) {
        for (let index = 0; index < STATE_SIZE; ++index) {
          this.vectors.state[index] = previousState[index] - multiplier * correction[index];
        }
        this._stationaryFunction(
          OFFSETS.state,
          time,
          OFFSETS.residual,
          OFFSETS.jacobian,
        );
        const candidateNorm = residualNorm();
        if (Number.isFinite(candidateNorm) && candidateNorm < norm) {
          norm = candidateNorm;
          improved = true;
          break;
        }
        multiplier *= 0.5;
      }
      if (!improved) {
        this.vectors.state.set(previousState);
        throw new Error(`Operating-point backtracking failed at t=${time} below step multiplier ${minimumStepMultiplier}`);
      }
      if (norm <= residualTolerance) return finish(iterations + 1, norm);
    }
    throw new Error(`Operating-point Newton iteration did not converge at t=${time} after ${iterations} iterations (residual norm ${norm})`);
  }

  newtonIteration(time, stepSize, pivotTolerance = 1e-14, residualTolerance = 1e-10, minimumStepMultiplier = 2 ** -20) {
    this._refreshViews();
    this._stepFunction(
      OFFSETS.stageDerivatives,
      time,
      stepSize,
      OFFSETS.state,
      OFFSETS.residual,
      OFFSETS.jacobian,
    );
    let residualNorm = 0;
    for (let index = 0; index < this.vectors.residual.length; ++index) {
      residualNorm = Math.max(residualNorm, Math.abs(this.vectors.residual[index]));
    }
    if (!Number.isFinite(residualNorm)) throw new Error("Newton residual is non-finite");
    if (residualNorm <= residualTolerance) {
      this.vectors.updatedStageDerivatives.set(this.vectors.stageDerivatives);
      for (let index = 0; index < STATE_SIZE; ++index) {
        this.vectors.nextState[index] = this.vectors.state[index] + stepSize * (
          3 / 4 * this.vectors.stageDerivatives[index]
          + 1 / 4 * this.vectors.stageDerivatives[STATE_SIZE + index]
        );
      }
      this._newtonResult.error = 0;
      this._newtonResult.scale = 0;
      this._newtonResult.residualNorm = residualNorm;
      return this._newtonResult;
    }
    const status = this._linearSolve(
      OFFSETS.jacobian,
      OFFSETS.residual,
      2 * STATE_SIZE,
      pivotTolerance,
    );
    if (status === 1) throw new Error("Newton Jacobian is singular or ill-conditioned");
    if (status !== 0) throw new Error("Newton Jacobian contains a non-finite pivot");

    const previousStage = this._transientPreviousStage;
    const correction = this._transientCorrection;
    previousStage.set(this.vectors.stageDerivatives);
    correction.set(this.vectors.residual);
    let multiplier = 1;
    let candidateNorm = Infinity;
    let improved = false;
    while (multiplier >= minimumStepMultiplier) {
      for (let index = 0; index < this.vectors.stageDerivatives.length; ++index) {
        this.vectors.stageDerivatives[index] = previousStage[index] - multiplier * correction[index];
      }
      this._stepFunction(
        OFFSETS.stageDerivatives,
        time,
        stepSize,
        OFFSETS.state,
        OFFSETS.residual,
        OFFSETS.jacobian,
      );
      candidateNorm = 0;
      for (let index = 0; index < this.vectors.residual.length; ++index) {
        candidateNorm = Math.max(candidateNorm, Math.abs(this.vectors.residual[index]));
      }
      if (Number.isFinite(candidateNorm) && candidateNorm < residualNorm) {
        improved = true;
        break;
      }
      multiplier *= 0.5;
    }
    if (!improved) {
      this.vectors.stageDerivatives.set(previousStage);
      throw new Error(`Transient Newton backtracking failed below step multiplier ${minimumStepMultiplier}`);
    }

    let error = 0;
    let scale = 0;
    for (let index = 0; index < this.vectors.stageDerivatives.length; ++index) {
      const updated = this.vectors.stageDerivatives[index];
      this.vectors.updatedStageDerivatives[index] = updated;
      error = Math.max(error, Math.abs(multiplier * correction[index]));
      scale = Math.max(scale, Math.abs(updated));
    }
    for (let index = 0; index < STATE_SIZE; ++index) {
      this.vectors.nextState[index] = this.vectors.state[index] + stepSize * (
        3 / 4 * this.vectors.updatedStageDerivatives[index]
        + 1 / 4 * this.vectors.updatedStageDerivatives[STATE_SIZE + index]
      );
    }
    this._newtonResult.error = error;
    this._newtonResult.scale = scale;
    this._newtonResult.residualNorm = candidateNorm;
    return this._newtonResult;
  }

  step(time, stepSize, options = {}) {
    const {
      maxIterations = 20,
      requireConvergence = true,
      pivotTolerance = 1e-14,
      residualTolerance = 1e-10,
      minimumStepMultiplier = 2 ** -20,
    } = options;
    if (!(stepSize > 0)) throw new RangeError("stepSize must be positive");
    if (!Number.isInteger(maxIterations) || maxIterations < 1) {
      throw new RangeError("maxIterations must be a positive integer");
    }
    if (!Number.isFinite(residualTolerance) || !(residualTolerance > 0)) throw new RangeError("residualTolerance must be positive and finite");

    let error = Infinity;
    let scale = 0;
    let residualNorm = Infinity;
    let iterations = 0;
    let failure = null;
    let converged = false;
    // The second Radau stage is the derivative at the preceding step's end.
    // Use it as a constant predictor for both stages.  Retaining the old first
    // stage is particularly harmful immediately after a discontinuous source.
    this.vectors.stageDerivatives.copyWithin(0, STATE_SIZE, 2 * STATE_SIZE);
    for (let attempt = 0; attempt < 2; ++attempt) {
      if (attempt === 1) this.vectors.stageDerivatives.fill(0);
      error = Infinity;
      scale = 0;
      residualNorm = Infinity;
      iterations = 0;
      failure = null;
      for (; iterations < maxIterations; ++iterations) {
        try {
          ({error, scale, residualNorm} = this.newtonIteration(time, stepSize, pivotTolerance, residualTolerance, minimumStepMultiplier));
        } catch (cause) {
          failure = cause;
          break;
        }
        if (residualNorm <= residualTolerance) {
          ++iterations;
          converged = true;
          break;
        }
      }
      if (converged) break;
    }
    if (failure) {
      throw new Error(`Transient solve failed at t=${time + stepSize}: ${failure.message}`, {cause: failure});
    }
    if (!converged && requireConvergence) {
      throw new Error(`Newton iteration did not converge at t=${time + stepSize} after ${iterations} iterations (residual norm ${residualNorm})`);
    }
    this.vectors.state.set(this.vectors.nextState);
    return {time: time + stepSize, iterations, converged, error, scale};
  }

  adaptiveStep(time, stepSize, options = {}) {
    const {
      relativeTolerance = 1e-4,
      voltageAbsoluteTolerance = 1e-7,
      currentAbsoluteTolerance = 1e-10,
      ...stepOptions
    } = options;
    if (!Number.isFinite(relativeTolerance) || !(relativeTolerance > 0)) throw new RangeError("relativeTolerance must be positive and finite");
    if (!Number.isFinite(voltageAbsoluteTolerance) || !(voltageAbsoluteTolerance > 0)) throw new RangeError("voltageAbsoluteTolerance must be positive and finite");
    if (!Number.isFinite(currentAbsoluteTolerance) || !(currentAbsoluteTolerance > 0)) throw new RangeError("currentAbsoluteTolerance must be positive and finite");

    const initialState = this._adaptiveInitialState;
    const initialStage = this._adaptiveInitialStage;
    const fullState = this._adaptiveFullState;
    initialState.set(this.vectors.state);
    initialStage.set(this.vectors.stageDerivatives);
    const restore = () => {
      this.vectors.state.set(initialState);
      this.vectors.stageDerivatives.set(initialStage);
    };

    try {
      this.step(time, stepSize, stepOptions);
      fullState.set(this.vectors.state);
      restore();
      const halfStep = stepSize / 2;
      this.step(time, halfStep, stepOptions);
      this.step(time + halfStep, halfStep, stepOptions);
    } catch (failure) {
      restore();
      return {accepted: false, errorNorm: Infinity, suggestedStep: stepSize * 0.25, failure};
    }

    let errorNorm = 0;
    for (let index = 0; index < STATE_SIZE; ++index) {
      const absoluteTolerance = index < POTENTIAL_COUNT ? voltageAbsoluteTolerance : currentAbsoluteTolerance;
      const scale = absoluteTolerance + relativeTolerance * Math.max(Math.abs(initialState[index]), Math.abs(this.vectors.state[index]));
      errorNorm = Math.max(errorNorm, Math.abs(this.vectors.state[index] - fullState[index]) / (7 * scale));
    }
    const factor = errorNorm === 0 ? 5 : Math.max(0.2, Math.min(5, 0.9 * errorNorm ** -0.25));
    if (!(errorNorm <= 1)) {
      restore();
      return {accepted: false, errorNorm, suggestedStep: stepSize * Math.min(0.9, factor), failure: null};
    }
    return {
      accepted: true,
      errorNorm,
      suggestedStep: stepSize * factor,
      endTime: time + stepSize,
    };
  }

  integrateAdaptiveArrays(options) {
    const {
      startTime,
      endTime,
      minimumStepSize,
      maximumStepSize,
      includeInitial = true,
      ...adaptiveOptions
    } = options;
    if (!(endTime >= startTime)) throw new RangeError("endTime must not precede startTime");
    if (!Number.isFinite(minimumStepSize) || !(minimumStepSize > 0)) throw new RangeError("minimumStepSize must be positive and finite");
    if (!Number.isFinite(maximumStepSize) || !(maximumStepSize >= minimumStepSize)) throw new RangeError("maximumStepSize must be finite and not smaller than minimumStepSize");

    let capacity = 256;
    let times = new Float64Array(capacity);
    let states = new Float64Array(capacity * STATE_SIZE);
    let auxiliaries = new Float64Array(capacity * AUXILIARY_COUNT);
    let sampleCount = 0;
    const reserve = required => {
      if (required <= capacity) return;
      while (capacity < required) capacity *= 2;
      const grownTimes = new Float64Array(capacity);
      const grownStates = new Float64Array(capacity * STATE_SIZE);
      const grownAuxiliaries = new Float64Array(capacity * AUXILIARY_COUNT);
      grownTimes.set(times.subarray(0, sampleCount));
      grownStates.set(states.subarray(0, sampleCount * STATE_SIZE));
      grownAuxiliaries.set(auxiliaries.subarray(0, sampleCount * AUXILIARY_COUNT));
      times = grownTimes;
      states = grownStates;
      auxiliaries = grownAuxiliaries;
    };
    const record = (time, state = this.vectors.state) => {
      reserve(sampleCount + 1);
      times[sampleCount] = time;
      states.set(state, sampleCount * STATE_SIZE);
      if (AUXILIARY_COUNT) auxiliaries.set(this._evaluateAuxiliaries(time), sampleCount * AUXILIARY_COUNT);
      ++sampleCount;
    };

    let time = startTime;
    let stepSize = Math.sqrt(minimumStepSize * maximumStepSize);
    let acceptedSteps = 0;
    let rejectedSteps = 0;
    if (includeInitial) record(time);
    while (time < endTime) {
      const remaining = endTime - time;
      const trialStep = Math.min(stepSize, maximumStepSize, remaining);
      if (!(trialStep > 0)) break;
      const result = this.adaptiveStep(time, trialStep, adaptiveOptions);
      if (!result.accepted) {
        ++rejectedSteps;
        const nextStep = Math.max(minimumStepSize, result.suggestedStep);
        if (trialStep <= minimumStepSize * (1 + 16 * Number.EPSILON) || remaining < minimumStepSize) {
          const reason = result.failure ? `: ${result.failure.message}` : ` (estimated error ${result.errorNorm})`;
          throw new Error(`Adaptive integration failed at t=${time}; minimum step size ${minimumStepSize} is insufficient${reason}`, {cause: result.failure ?? undefined});
        }
        stepSize = nextStep;
        continue;
      }
      record(result.endTime);
      time = result.endTime;
      ++acceptedSteps;
      stepSize = Math.max(minimumStepSize, Math.min(maximumStepSize, result.suggestedStep));
    }
    return {
      times: times.subarray(0, sampleCount),
      states: states.subarray(0, sampleCount * STATE_SIZE),
      auxiliaries: auxiliaries.subarray(0, sampleCount * AUXILIARY_COUNT),
      auxiliaryCount: AUXILIARY_COUNT,
      sampleCount,
      stateSize: STATE_SIZE,
      acceptedSteps,
      rejectedSteps,
    };
  }

  *integrate(options) {
    const {
      startTime,
      endTime,
      stepSize,
      includeInitial = true,
      ...stepOptions
    } = options;
    if (!(endTime >= startTime)) throw new RangeError("endTime must not precede startTime");
    if (!(stepSize > 0)) throw new RangeError("stepSize must be positive");

    let time = startTime;
    if (includeInitial) {
      yield {time, initial: true, state: this.state.snapshot()};
    }
    const stepCount = Math.ceil((endTime - startTime) / stepSize);
    for (let stepIndex = 0; stepIndex < stepCount; ++stepIndex) {
      const targetTime = Math.min(endTime, startTime + (stepIndex + 1) * stepSize);
      const currentStep = targetTime - time;
      if (!(currentStep > 0)) break;
      const result = this.step(time, currentStep, stepOptions);
      time = targetTime;
      yield {...result, time, initial: false, state: this.state.snapshot()};
    }
  }

  integrateArrays(options) {
    const {
      startTime,
      endTime,
      stepSize,
      includeInitial = true,
      ...stepOptions
    } = options;
    if (!(endTime >= startTime)) throw new RangeError("endTime must not precede startTime");
    if (!(stepSize > 0)) throw new RangeError("stepSize must be positive");
    const stepCount = Math.ceil((endTime - startTime) / stepSize);
    const capacity = stepCount + (includeInitial ? 1 : 0);
    const times = new Float64Array(capacity);
    const states = new Float64Array(capacity * STATE_SIZE);
    const auxiliaries = new Float64Array(capacity * AUXILIARY_COUNT);
    let sampleCount = 0;
    const record = time => {
      times[sampleCount] = time;
      states.set(this.vectors.state, sampleCount * STATE_SIZE);
      if (AUXILIARY_COUNT) auxiliaries.set(this._evaluateAuxiliaries(time), sampleCount * AUXILIARY_COUNT);
      ++sampleCount;
    };
    let time = startTime;
    if (includeInitial) record(time);
    for (let stepIndex = 0; stepIndex < stepCount; ++stepIndex) {
      const targetTime = Math.min(endTime, startTime + (stepIndex + 1) * stepSize);
      const currentStep = targetTime - time;
      if (!(currentStep > 0)) break;
      this.step(time, currentStep, stepOptions);
      time = targetTime;
      record(time);
    }
    return {
      times: sampleCount === capacity ? times : times.subarray(0, sampleCount),
      states: sampleCount === capacity ? states : states.subarray(0, sampleCount * STATE_SIZE),
      auxiliaries: sampleCount === capacity ? auxiliaries : auxiliaries.subarray(0, sampleCount * AUXILIARY_COUNT),
      auxiliaryCount: AUXILIARY_COUNT,
      sampleCount,
      stateSize: STATE_SIZE,
    };
  }
}

export const circuitLayout = Object.freeze({
  stateSize: STATE_SIZE,
  potentials: POTENTIAL_INDICES,
  currents: CURRENT_INDICES,
  auxiliaries: AUXILIARY_INDICES,
  offsets: OFFSETS,
});
