format = 1

include = [
  "library/models/passive.toml",
  "library/models/magnetic.toml",
  "library/models/sources.toml",
  "library/models/diode.toml",
  "library/models/bjt-transistor.toml",
  "library/models/fet.toml",
  "library/models/opamp.toml",
  "library/parts/diodes.toml",
  "library/parts/npn-transistors.toml",
  "library/parts/pnp-transistors.toml",
  "library/parts/fets.toml",
]
