"""Generate a high-level JavaScript wrapper for a WebAssembly Radau solver."""

import json
import re

from .compiler import EquationSystem, radau_memory_layout


def generate_javascript_radau_wrapper(
    system: EquationSystem,
    *,
    class_name: str = "AntispiceSolver",
    function_name: str = "radau_newton_step",
) -> str:
    """Generate an ES module wrapping the flattened WebAssembly solver ABI.

    The resulting class exposes live flat vectors through ``solver.vectors``
    and structured access through ``solver.state``.  Its ``step`` method runs
    Newton iterations for one timestep, while ``integrate`` yields snapshots
    over a time interval.
    """
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", class_name) is None:
        raise ValueError(f"invalid JavaScript class name: {class_name!r}")

    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", function_name) is None:
        raise ValueError(f"invalid WebAssembly function name: {function_name!r}")

    memory = radau_memory_layout(system)
    potentials = system.layout.potentials
    currents: dict[str, dict[str, int]] = {}

    for (reference, port), index in system.layout.currents.items():
        currents.setdefault(reference, {})[port] = index

    source = _JAVASCRIPT_TEMPLATE
    replacements = {
        "__CLASS_NAME__": class_name,
        "__FUNCTION_NAME__": json.dumps(function_name),
        "__STATE_SIZE__": str(len(system.state)),
        "__POTENTIALS__": json.dumps(potentials, ensure_ascii=False),
        "__CURRENTS__": json.dumps(currents, ensure_ascii=False),
        "__STAGE_DERIVATIVES__": str(memory.stage_derivatives),
        "__PREVIOUS_STATE__": str(memory.previous_state),
        "__UPDATED_STAGE_DERIVATIVES__": str(memory.updated_stage_derivatives),
        "__NEXT_STATE__": str(memory.next_state),
    }

    for marker, value in replacements.items():
        source = source.replace(marker, value)

    return source


_JAVASCRIPT_TEMPLATE = r"""// Machine generated by antispice.
const FUNCTION_NAME = __FUNCTION_NAME__;
const STATE_SIZE = __STATE_SIZE__;
const POTENTIAL_INDICES = Object.freeze(__POTENTIALS__);
const CURRENT_INDICES = Object.freeze(__CURRENTS__);
const OFFSETS = Object.freeze({
  stageDerivatives: __STAGE_DERIVATIVES__,
  state: __PREVIOUS_STATE__,
  updatedStageDerivatives: __UPDATED_STAGE_DERIVATIVES__,
  nextState: __NEXT_STATE__,
});

const DEFAULT_MATH_IMPORTS = Object.freeze({
  abs: Math.abs,
  acos: Math.acos,
  acosh: Math.acosh,
  asin: Math.asin,
  asinh: Math.asinh,
  atan: Math.atan,
  atan2: Math.atan2,
  atanh: Math.atanh,
  cos: Math.cos,
  cosh: Math.cosh,
  exp: Math.exp,
  log: Math.log,
  powf: Math.pow,
  powi: (base, exponent) => Math.pow(base, Number(exponent)),
  sin: Math.sin,
  sinh: Math.sinh,
  tan: Math.tan,
  tanh: Math.tanh,
});

class CircuitStateView {
  constructor(owner) {
    this._owner = owner;
  }

  get vector() {
    this._owner._refreshViews();
    return this._owner.vectors.state;
  }

  potential(net) {
    if (net === "0") return 0;
    const index = POTENTIAL_INDICES[net];
    if (index === undefined) throw new RangeError(`Unknown net: ${net}`);
    return this.vector[index];
  }

  setPotential(net, value) {
    if (net === "0") throw new RangeError("The reference potential is fixed at zero");
    const index = POTENTIAL_INDICES[net];
    if (index === undefined) throw new RangeError(`Unknown net: ${net}`);
    this.vector[index] = value;
  }

  current(reference, port) {
    const ports = CURRENT_INDICES[reference];
    if (ports === undefined || ports[port] === undefined) {
      throw new RangeError(`Unknown element port: ${reference}.${port}`);
    }
    return this.vector[ports[port]];
  }

  setCurrent(reference, port, value) {
    const ports = CURRENT_INDICES[reference];
    if (ports === undefined || ports[port] === undefined) {
      throw new RangeError(`Unknown element port: ${reference}.${port}`);
    }
    this.vector[ports[port]] = value;
  }

  snapshot() {
    const vector = Array.from(this.vector);
    const potentials = {"0": 0};
    for (const [net, index] of Object.entries(POTENTIAL_INDICES)) {
      potentials[net] = vector[index];
    }
    const currents = {};
    for (const [reference, ports] of Object.entries(CURRENT_INDICES)) {
      currents[reference] = {};
      for (const [port, index] of Object.entries(ports)) {
        currents[reference][port] = vector[index];
      }
    }
    return {vector, potentials, currents};
  }
}

export class __CLASS_NAME__ {
  static async instantiate(source, imports = {}) {
    const mergedImports = {
      ...imports,
      math: {...DEFAULT_MATH_IMPORTS, ...(imports.math || {})},
    };
    let instance;
    if (source instanceof WebAssembly.Instance) {
      instance = source;
    } else if (source instanceof WebAssembly.Module) {
      instance = await WebAssembly.instantiate(source, mergedImports);
    } else {
      let bytes = source;
      if (typeof Response !== "undefined" && source instanceof Response) {
        bytes = await source.arrayBuffer();
      }
      const result = await WebAssembly.instantiate(bytes, mergedImports);
      instance = result.instance;
    }
    return new __CLASS_NAME__(instance);
  }

  constructor(instance) {
    this.instance = instance;
    this.memory = instance.exports.memory;
    this._stepFunction = instance.exports[FUNCTION_NAME];
    if (!(this.memory instanceof WebAssembly.Memory)) {
      throw new TypeError("The WebAssembly module does not export memory");
    }
    if (typeof this._stepFunction !== "function") {
      throw new TypeError(`The WebAssembly module does not export ${FUNCTION_NAME}`);
    }
    this._buffer = null;
    this.vectors = null;
    this._refreshViews();
    this.state = new CircuitStateView(this);
  }

  _refreshViews() {
    if (this._buffer === this.memory.buffer) return;
    this._buffer = this.memory.buffer;
    this.vectors = Object.freeze({
      stageDerivatives: new Float64Array(this._buffer, OFFSETS.stageDerivatives, 2 * STATE_SIZE),
      state: new Float64Array(this._buffer, OFFSETS.state, STATE_SIZE),
      updatedStageDerivatives: new Float64Array(this._buffer, OFFSETS.updatedStageDerivatives, 2 * STATE_SIZE),
      nextState: new Float64Array(this._buffer, OFFSETS.nextState, STATE_SIZE),
    });
  }

  reset(value = 0) {
    this._refreshViews();
    for (const vector of Object.values(this.vectors)) vector.fill(value);
  }

  newtonIteration(time, stepSize) {
    this._refreshViews();
    this._stepFunction(
      OFFSETS.stageDerivatives,
      time,
      stepSize,
      OFFSETS.state,
      OFFSETS.updatedStageDerivatives,
      OFFSETS.nextState,
    );

    let error = 0;
    let scale = 0;
    for (let index = 0; index < this.vectors.stageDerivatives.length; ++index) {
      const previous = this.vectors.stageDerivatives[index];
      const updated = this.vectors.updatedStageDerivatives[index];
      error = Math.max(error, Math.abs(updated - previous));
      scale = Math.max(scale, Math.abs(updated));
    }
    this.vectors.stageDerivatives.set(this.vectors.updatedStageDerivatives);
    return {error, scale};
  }

  step(time, stepSize, options = {}) {
    const {
      maxIterations = 10,
      absoluteTolerance = 1e-10,
      relativeTolerance = 1e-8,
      requireConvergence = true,
    } = options;
    if (!(stepSize > 0)) throw new RangeError("stepSize must be positive");
    if (!Number.isInteger(maxIterations) || maxIterations < 1) {
      throw new RangeError("maxIterations must be a positive integer");
    }

    let error = Infinity;
    let scale = 0;
    let iterations = 0;
    for (; iterations < maxIterations; ++iterations) {
      ({error, scale} = this.newtonIteration(time, stepSize));
      if (error <= absoluteTolerance + relativeTolerance * scale) {
        ++iterations;
        break;
      }
    }
    const converged = error <= absoluteTolerance + relativeTolerance * scale;
    if (!converged && requireConvergence) {
      throw new Error(`Newton iteration did not converge after ${iterations} iterations`);
    }
    this.vectors.state.set(this.vectors.nextState);
    return {time: time + stepSize, iterations, converged, error, scale};
  }

  *integrate(options) {
    const {
      startTime,
      endTime,
      stepSize,
      includeInitial = true,
      ...stepOptions
    } = options;
    if (!(endTime >= startTime)) throw new RangeError("endTime must not precede startTime");
    if (!(stepSize > 0)) throw new RangeError("stepSize must be positive");

    let time = startTime;
    if (includeInitial) {
      yield {time, initial: true, state: this.state.snapshot()};
    }
    while (time < endTime) {
      const currentStep = Math.min(stepSize, endTime - time);
      if (!(currentStep > 0)) break;
      const result = this.step(time, currentStep, stepOptions);
      time = result.time;
      yield {...result, initial: false, state: this.state.snapshot()};
    }
  }
}

export const circuitLayout = Object.freeze({
  stateSize: STATE_SIZE,
  potentials: POTENTIAL_INDICES,
  currents: CURRENT_INDICES,
  offsets: OFFSETS,
});
"""
